# Site settings
title: Zy Blog
SEOTitle: 赵宇的博客 | Zy Blog
header-img: img/home-bg.jpg
email: your-email@example.com # 替换为你的实际邮箱
description: "这里是赵宇的个人博客，记录技术成长、生活思考与学习笔记，与你一起探索技术与生活的边界"
keyword: "赵宇, Zy, 赵宇的博客, Zy Blog, 博客, 个人网站, 技术分享, 学习笔记, 前端, 编程, 开发"
url: "https://fuoins.github.io" # 你的博客域名（无需修改，保持 GitHub Pages 地址）
baseurl: "" # 若博客部署在子目录则填写（如 '/blog'），此处默认无需修改

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: # 可选：填写你的微博用户名（无则留空）
zhihu_username: # 可选：填写你的知乎用户名（无则留空）
github_username: fuoins # 你的 GitHub 用户名（已默认填充）
twitter_username: # 可选：填写你的 Twitter 用户名（无则留空）
#facebook_username: # 可选：填写你的 Facebook 用户名（无则留空）
#linkedin_username: # 可选：填写你的 LinkedIn 用户名（无则留空）

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN # 中国时区（已启用，避免时间显示异常）

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings（评论功能，无需则可留空）
disqus_username: # 可选：填写你的 Disqus 用户名（无则留空，关闭评论）

# Netease settings（网易云评论，无需则保持关闭）
netease_comment: false

# Analytics settings（统计功能，按需配置）
# Baidu Analytics（百度统计）
# ba_track_id: [your baidu track id] # 可选：填写百度统计跟踪ID（无则留空）

# Google Analytics（谷歌统计）
ga_track_id: "" # 可选：填写谷歌统计跟踪ID（格式 UA-xxxxxx-xx，无则留空）
ga_domain: fuoins.github.io # 谷歌统计关联域名（与博客域名一致）

# Sidebar settings（侧边栏配置）
sidebar: true # 是否显示侧边栏（保持开启）
sidebar-about-description: "热爱技术，乐于分享 <br> 持续学习，稳步成长" # 个人简介（可自定义修改）
sidebar-avatar: # 可选：填写头像绝对路径（如 https://github.com/fuoins.png，无则留空）

# Featured Tags（精选标签功能）
featured-tags: true # 是否启用精选标签
featured-condition-size: 1 # 标签下文章数超过此数值则显示为精选标签

# Progressive Web Apps（渐进式Web应用）
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)（数学公式渲染，无需则保持关闭）
page-mathjax: false

# Friends（友链，已按需求删除原列表，无需则保持空数组）
friends: []
